/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SwapHelperInterface extends Interface {
  getFunction(nameOrSignature: "dexRouter" | "getSwapQuote"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DEXRouterUpdated" | "SwapExecuted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "dexRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSwapQuote",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "dexRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSwapQuote",
    data: BytesLike
  ): Result;
}

export namespace DEXRouterUpdatedEvent {
  export type InputTuple = [newRouter: AddressLike];
  export type OutputTuple = [newRouter: string];
  export interface OutputObject {
    newRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    fromToken: AddressLike,
    toToken: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    slippageBps: BigNumberish
  ];
  export type OutputTuple = [
    fromToken: string,
    toToken: string,
    amountIn: bigint,
    amountOut: bigint,
    slippageBps: bigint
  ];
  export interface OutputObject {
    fromToken: string;
    toToken: string;
    amountIn: bigint;
    amountOut: bigint;
    slippageBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwapHelper extends BaseContract {
  connect(runner?: ContractRunner | null): SwapHelper;
  waitForDeployment(): Promise<this>;

  interface: SwapHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dexRouter: TypedContractMethod<[], [string], "view">;

  getSwapQuote: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amountIn: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dexRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSwapQuote"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amountIn: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "DEXRouterUpdated"
  ): TypedContractEvent<
    DEXRouterUpdatedEvent.InputTuple,
    DEXRouterUpdatedEvent.OutputTuple,
    DEXRouterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;

  filters: {
    "DEXRouterUpdated(address)": TypedContractEvent<
      DEXRouterUpdatedEvent.InputTuple,
      DEXRouterUpdatedEvent.OutputTuple,
      DEXRouterUpdatedEvent.OutputObject
    >;
    DEXRouterUpdated: TypedContractEvent<
      DEXRouterUpdatedEvent.InputTuple,
      DEXRouterUpdatedEvent.OutputTuple,
      DEXRouterUpdatedEvent.OutputObject
    >;

    "SwapExecuted(address,address,uint256,uint256,uint256)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
  };
}
