/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  MockRedemptionPriceOracle,
  MockRedemptionPriceOracleInterface,
} from "../../../../../contracts/src/mocks/MockUSDY.sol/MockRedemptionPriceOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_usdy",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdy",
    outputs: [
      {
        internalType: "contract MockUSDY",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60803461007457601f6101e038819003918201601f19168301916001600160401b038311848410176100795780849260209460405283398101031261007457516001600160a01b0381169081900361007457600080546001600160a01b03191691909117905560405161015090816100908239f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe608080604052600436101561001357600080fd5b600090813560e01c90816398d506e9146100f657506398d5fdca1461003757600080fd5b346100f357806003193601126100f3578054604051630316dd2360e61b815290602090829060049082906001600160a01b03165afa9081156100e8578291610085575b602082604051908152f35b905060203d81116100e1575b601f8101601f1916820167ffffffffffffffff8111838210176100cd576020918391604052810103126100c95760209150513861007a565b5080fd5b634e487b7160e01b84526041600452602484fd5b503d610091565b6040513d84823e3d90fd5b80fd5b9050346100c957816003193601126100c95790546001600160a01b03168152602090f3fea2646970667358221220ab205f2ca5ec477b953895bfde898ad1e2bf4db2a1082ba340f14dccee998de564736f6c63430008140033";

type MockRedemptionPriceOracleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockRedemptionPriceOracleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockRedemptionPriceOracle__factory extends ContractFactory {
  constructor(...args: MockRedemptionPriceOracleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _usdy: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_usdy, overrides || {});
  }
  override deploy(
    _usdy: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_usdy, overrides || {}) as Promise<
      MockRedemptionPriceOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockRedemptionPriceOracle__factory {
    return super.connect(runner) as MockRedemptionPriceOracle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockRedemptionPriceOracleInterface {
    return new Interface(_abi) as MockRedemptionPriceOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockRedemptionPriceOracle {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockRedemptionPriceOracle;
  }
}
