/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface DateTimeTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "testGetDay"
      | "testGetDaysInMonth"
      | "testGetMonth"
      | "testGetYear"
      | "testIsLeapYear"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "testGetDay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testGetDaysInMonth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testGetMonth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testGetYear",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testIsLeapYear",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "testGetDay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testGetDaysInMonth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testGetMonth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testGetYear",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testIsLeapYear",
    data: BytesLike
  ): Result;
}

export interface DateTimeTest extends BaseContract {
  connect(runner?: ContractRunner | null): DateTimeTest;
  waitForDeployment(): Promise<this>;

  interface: DateTimeTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  testGetDay: TypedContractMethod<[timestamp: BigNumberish], [bigint], "view">;

  testGetDaysInMonth: TypedContractMethod<
    [timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  testGetMonth: TypedContractMethod<
    [timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  testGetYear: TypedContractMethod<[timestamp: BigNumberish], [bigint], "view">;

  testIsLeapYear: TypedContractMethod<
    [timestamp: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "testGetDay"
  ): TypedContractMethod<[timestamp: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "testGetDaysInMonth"
  ): TypedContractMethod<[timestamp: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "testGetMonth"
  ): TypedContractMethod<[timestamp: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "testGetYear"
  ): TypedContractMethod<[timestamp: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "testIsLeapYear"
  ): TypedContractMethod<[timestamp: BigNumberish], [boolean], "view">;

  filters: {};
}
