/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iLendleSol from "./ILendle.sol";
export type { iLendleSol };
import type * as iMethSol from "./IMeth.sol";
export type { iMethSol };
import type * as iOndoSol from "./IOndo.sol";
export type { iOndoSol };
export type { IDEXRouter } from "./IDEXRouter";
export type { ISweepKeeper } from "./ISweepKeeper";
