/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ISweepKeeperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeAutoSweep"
      | "billsBucket"
      | "checker"
      | "executeSweep"
      | "getDayOfMonth"
      | "getDaysInMonth"
      | "getHighestYieldBucket"
      | "getLastSweepTimestamp"
      | "getSweepableAmount"
      | "getTimeUntilNextSweep"
      | "getUserMinimumBalance"
      | "globalMinimumBalance"
      | "growthBucket"
      | "isAuthorized"
      | "isMonthEnd"
      | "isPaused"
      | "pause"
      | "revokeAutoSweep"
      | "savingsBucket"
      | "setBucketAddresses"
      | "setGlobalMinimumBalance"
      | "setUserMinimumBalance"
      | "spendableBucket"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizationChanged"
      | "BucketAddressesUpdated"
      | "GlobalMinimumBalanceUpdated"
      | "SweepExecuted"
      | "UserMinimumBalanceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeAutoSweep",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "billsBucket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSweep",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDayOfMonth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDaysInMonth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHighestYieldBucket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastSweepTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSweepableAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeUntilNextSweep",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMinimumBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalMinimumBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "growthBucket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMonthEnd",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeAutoSweep",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "savingsBucket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBucketAddresses",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalMinimumBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserMinimumBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "spendableBucket",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "authorizeAutoSweep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "billsBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeSweep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDayOfMonth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDaysInMonth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHighestYieldBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastSweepTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSweepableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeUntilNextSweep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMinimumBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalMinimumBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "growthBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMonthEnd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeAutoSweep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "savingsBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBucketAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalMinimumBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserMinimumBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendableBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AuthorizationChangedEvent {
  export type InputTuple = [user: AddressLike, authorized: boolean];
  export type OutputTuple = [user: string, authorized: boolean];
  export interface OutputObject {
    user: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BucketAddressesUpdatedEvent {
  export type InputTuple = [
    bills: AddressLike,
    savings: AddressLike,
    growth: AddressLike,
    spendable: AddressLike
  ];
  export type OutputTuple = [
    bills: string,
    savings: string,
    growth: string,
    spendable: string
  ];
  export interface OutputObject {
    bills: string;
    savings: string;
    growth: string;
    spendable: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalMinimumBalanceUpdatedEvent {
  export type InputTuple = [newMinimum: BigNumberish];
  export type OutputTuple = [newMinimum: bigint];
  export interface OutputObject {
    newMinimum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SweepExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fromBucket: AddressLike,
    toBucket: AddressLike,
    expectedYield: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    fromBucket: string,
    toBucket: string,
    expectedYield: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fromBucket: string;
    toBucket: string;
    expectedYield: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserMinimumBalanceUpdatedEvent {
  export type InputTuple = [user: AddressLike, newMinimum: BigNumberish];
  export type OutputTuple = [user: string, newMinimum: bigint];
  export interface OutputObject {
    user: string;
    newMinimum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISweepKeeper extends BaseContract {
  connect(runner?: ContractRunner | null): ISweepKeeper;
  waitForDeployment(): Promise<this>;

  interface: ISweepKeeperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeAutoSweep: TypedContractMethod<[], [void], "nonpayable">;

  billsBucket: TypedContractMethod<[], [string], "view">;

  checker: TypedContractMethod<
    [user: AddressLike],
    [[boolean, string] & { canExec: boolean; execPayload: string }],
    "view"
  >;

  executeSweep: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  getDayOfMonth: TypedContractMethod<[], [bigint], "view">;

  getDaysInMonth: TypedContractMethod<[], [bigint], "view">;

  getHighestYieldBucket: TypedContractMethod<
    [],
    [[string, bigint] & { bucket: string; yieldRate: bigint }],
    "view"
  >;

  getLastSweepTimestamp: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getSweepableAmount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getTimeUntilNextSweep: TypedContractMethod<[], [bigint], "view">;

  getUserMinimumBalance: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  globalMinimumBalance: TypedContractMethod<[], [bigint], "view">;

  growthBucket: TypedContractMethod<[], [string], "view">;

  isAuthorized: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isMonthEnd: TypedContractMethod<[], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  revokeAutoSweep: TypedContractMethod<[], [void], "nonpayable">;

  savingsBucket: TypedContractMethod<[], [string], "view">;

  setBucketAddresses: TypedContractMethod<
    [
      bills: AddressLike,
      savings: AddressLike,
      growth: AddressLike,
      spendable: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setGlobalMinimumBalance: TypedContractMethod<
    [minimum: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUserMinimumBalance: TypedContractMethod<
    [minimum: BigNumberish],
    [void],
    "nonpayable"
  >;

  spendableBucket: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeAutoSweep"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "billsBucket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checker"
  ): TypedContractMethod<
    [user: AddressLike],
    [[boolean, string] & { canExec: boolean; execPayload: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeSweep"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDayOfMonth"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDaysInMonth"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHighestYieldBucket"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { bucket: string; yieldRate: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLastSweepTimestamp"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSweepableAmount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTimeUntilNextSweep"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserMinimumBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalMinimumBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "growthBucket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMonthEnd"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAutoSweep"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "savingsBucket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBucketAddresses"
  ): TypedContractMethod<
    [
      bills: AddressLike,
      savings: AddressLike,
      growth: AddressLike,
      spendable: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGlobalMinimumBalance"
  ): TypedContractMethod<[minimum: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserMinimumBalance"
  ): TypedContractMethod<[minimum: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "spendableBucket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AuthorizationChanged"
  ): TypedContractEvent<
    AuthorizationChangedEvent.InputTuple,
    AuthorizationChangedEvent.OutputTuple,
    AuthorizationChangedEvent.OutputObject
  >;
  getEvent(
    key: "BucketAddressesUpdated"
  ): TypedContractEvent<
    BucketAddressesUpdatedEvent.InputTuple,
    BucketAddressesUpdatedEvent.OutputTuple,
    BucketAddressesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalMinimumBalanceUpdated"
  ): TypedContractEvent<
    GlobalMinimumBalanceUpdatedEvent.InputTuple,
    GlobalMinimumBalanceUpdatedEvent.OutputTuple,
    GlobalMinimumBalanceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SweepExecuted"
  ): TypedContractEvent<
    SweepExecutedEvent.InputTuple,
    SweepExecutedEvent.OutputTuple,
    SweepExecutedEvent.OutputObject
  >;
  getEvent(
    key: "UserMinimumBalanceUpdated"
  ): TypedContractEvent<
    UserMinimumBalanceUpdatedEvent.InputTuple,
    UserMinimumBalanceUpdatedEvent.OutputTuple,
    UserMinimumBalanceUpdatedEvent.OutputObject
  >;

  filters: {
    "AuthorizationChanged(address,bool)": TypedContractEvent<
      AuthorizationChangedEvent.InputTuple,
      AuthorizationChangedEvent.OutputTuple,
      AuthorizationChangedEvent.OutputObject
    >;
    AuthorizationChanged: TypedContractEvent<
      AuthorizationChangedEvent.InputTuple,
      AuthorizationChangedEvent.OutputTuple,
      AuthorizationChangedEvent.OutputObject
    >;

    "BucketAddressesUpdated(address,address,address,address)": TypedContractEvent<
      BucketAddressesUpdatedEvent.InputTuple,
      BucketAddressesUpdatedEvent.OutputTuple,
      BucketAddressesUpdatedEvent.OutputObject
    >;
    BucketAddressesUpdated: TypedContractEvent<
      BucketAddressesUpdatedEvent.InputTuple,
      BucketAddressesUpdatedEvent.OutputTuple,
      BucketAddressesUpdatedEvent.OutputObject
    >;

    "GlobalMinimumBalanceUpdated(uint256)": TypedContractEvent<
      GlobalMinimumBalanceUpdatedEvent.InputTuple,
      GlobalMinimumBalanceUpdatedEvent.OutputTuple,
      GlobalMinimumBalanceUpdatedEvent.OutputObject
    >;
    GlobalMinimumBalanceUpdated: TypedContractEvent<
      GlobalMinimumBalanceUpdatedEvent.InputTuple,
      GlobalMinimumBalanceUpdatedEvent.OutputTuple,
      GlobalMinimumBalanceUpdatedEvent.OutputObject
    >;

    "SweepExecuted(address,uint256,address,address,uint256,uint256)": TypedContractEvent<
      SweepExecutedEvent.InputTuple,
      SweepExecutedEvent.OutputTuple,
      SweepExecutedEvent.OutputObject
    >;
    SweepExecuted: TypedContractEvent<
      SweepExecutedEvent.InputTuple,
      SweepExecutedEvent.OutputTuple,
      SweepExecutedEvent.OutputObject
    >;

    "UserMinimumBalanceUpdated(address,uint256)": TypedContractEvent<
      UserMinimumBalanceUpdatedEvent.InputTuple,
      UserMinimumBalanceUpdatedEvent.OutputTuple,
      UserMinimumBalanceUpdatedEvent.OutputObject
    >;
    UserMinimumBalanceUpdated: TypedContractEvent<
      UserMinimumBalanceUpdatedEvent.InputTuple,
      UserMinimumBalanceUpdatedEvent.OutputTuple,
      UserMinimumBalanceUpdatedEvent.OutputObject
    >;
  };
}
