/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILendlePool,
  ILendlePoolInterface,
} from "../../../../../contracts/src/interfaces/ILendle.sol/ILendlePool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getReserveData",
    outputs: [
      {
        internalType: "uint256",
        name: "configuration",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "liquidityIndex",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "currentLiquidityRate",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "variableBorrowIndex",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "currentVariableBorrowRate",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "currentStableBorrowRate",
        type: "uint128",
      },
      {
        internalType: "uint40",
        name: "lastUpdateTimestamp",
        type: "uint40",
      },
      {
        internalType: "uint16",
        name: "id",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "aTokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "stableDebtTokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "variableDebtTokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "interestRateStrategyAddress",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "accruedToTreasury",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "unbacked",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "isolationModeTotalDebt",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "onBehalfOf",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "referralCode",
        type: "uint16",
      },
    ],
    name: "supply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "withdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILendlePool__factory {
  static readonly abi = _abi;
  static createInterface(): ILendlePoolInterface {
    return new Interface(_abi) as ILendlePoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILendlePool {
    return new Contract(address, _abi, runner) as unknown as ILendlePool;
  }
}
