/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMethStaking,
  IMethStakingInterface,
} from "../../../../../contracts/src/interfaces/IMeth.sol/IMethStaking";

const _abi = [
  {
    inputs: [],
    name: "getAPY",
    outputs: [
      {
        internalType: "uint256",
        name: "apy",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "mETHAmount",
        type: "uint256",
      },
    ],
    name: "mETHToETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stake",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "unstake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMethStaking__factory {
  static readonly abi = _abi;
  static createInterface(): IMethStakingInterface {
    return new Interface(_abi) as IMethStakingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMethStaking {
    return new Contract(address, _abi, runner) as unknown as IMethStaking;
  }
}
